dist: xenial

language: python

matrix:
  include:
  - python: "3.7"
    env: STEP=lint
  - python: "3.7"
    env: STEP=mypy
  - python: "3.7"
    env: STEP=verify_import

install:
  - make update

script: make $STEP
