version: "3"

services:
  rocketchat:
    image: rocketchat/rocket.chat:0.74.3
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat

    depends_on:
      - mongo
    links:
      - mongo:mongo

  mongo:
    image: mongo:4.0
    restart: always
    command: mongod --smallfiles
    ports:
        - "27017:27017"
