[mypy]
check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_defs = True
no_implicit_optional = True
show_traceback = True
strict_optional = True
warn_no_return = True
warn_redundant_casts = True
# False due to missing typings in library
# Returntype of ddp_asyncio.subscription is better than Any
disallow_any_unimported = False
# False due to bug: https://github.com/python/mypy/issues/5957
warn_unused_configs = False

[mypy-ejson]
ignore_missing_imports = True

[mypy-pytz.tzinfo]
ignore_missing_imports = True

[mypy-tzlocal]
ignore_missing_imports = True

[mypy-ddp_asyncio.*]
ignore_missing_imports = True

[mypy-rocketchat_API.*]
ignore_missing_imports = True

[mypy-dmsclient]
ignore_missing_imports = True

[mypy-petname]
ignore_missing_imports = True

[mypy-bot_config]
ignore_missing_imports = True

[mypy-setuptools]
ignore_missing_imports = True
